# Site settings
title: Deep Labs
email: contact@deep-labs.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "deep-labs.com" # the subpath of your site, e.g. /blog/
url: "deep-labs.com" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
